<script setup>
import { computed, onBeforeUnmount, onMounted, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import { useDeviceStore } from "../stores/device.js";
import PageTitle from "../components/PageTitle.vue";
import VirtualGamepad from "../components/VirtualGamepad.vue";
import { createBlankStep, macroCycleMs, normalizeMacro, normalizeMacroDocument, serializeMacroDocument, validateMacro } from "../utils/macro-editor.js";
import { applyControlsToStep, controlsForReport } from "../utils/manual-input.js";
import { describeMacroStep } from "../utils/action-description.js";
const route = useRoute(); const router = useRouter(); const device = useDeviceStore();
const slotIndex = Number(route.params.slot); const slot = computed(() => device.slots[slotIndex]);
const name = ref(slot.value?.occupied ? slot.value.name : ""); const macro = ref({ steps: [createBlankStep()], loopGapMs: 0, repeat: true });
const message = ref(""); const loading = ref(false); const file = ref(null); const jsonPreview = ref(""); const jsonPreviewVisible = ref(false); const gamepadExamplesVisible = ref(true); const stepGamepadExamplesOverrides = ref(new Map()); const toast = ref(""); let toastTimer = null;
onMounted(async () => { const recorded = sessionStorage.getItem("splatoon-recorder-draft"); if (recorded) { const draft = JSON.parse(recorded); sessionStorage.removeItem("splatoon-recorder-draft"); name.value = draft.name || name.value; macro.value = normalizeMacro({ steps: draft.steps, loopGapMs: 0, repeat: true }); message.value = "已载入刚才的录制草稿，尚未写入 Flash。"; return; } if (!device.ready || !slot.value?.occupied) return; loading.value = true; try { const loaded = await device.loadMacro(slotIndex); macro.value = normalizeMacro(loaded); macro.value.repeat = true; name.value = loaded.name || slot.value.name; } catch (error) { message.value = error.message; } finally { loading.value = false; } });
onBeforeUnmount(() => clearTimeout(toastTimer));
function addStep(index = macro.value.steps.length) { const step = createBlankStep(); macro.value.steps.splice(index, 0, step); if (!gamepadExamplesVisible.value) { const overrides = new Map(stepGamepadExamplesOverrides.value); overrides.set(step, true); stepGamepadExamplesOverrides.value = overrides; } }
function removeStep(index) { if (macro.value.steps.length > 1) macro.value.steps.splice(index, 1); }
function moveStep(index, offset) { const target = index + offset; if (target < 0 || target >= macro.value.steps.length) return; const [step] = macro.value.steps.splice(index, 1); macro.value.steps.splice(target, 0, step); }
function updateControls(step, controls) { Object.assign(step, applyControlsToStep(step, controls)); }
async function save() { if (!name.value.trim()) { message.value = "请输入宏名称。"; return; } const errors = validateMacro(macro.value); if (errors.length) { message.value = errors[0]; return; } loading.value = true; try { await device.saveMacro(slotIndex, name.value, macro.value); message.value = "宏已写入 Flash，可以加入宏循环。"; } catch (error) { message.value = error.message; } finally { loading.value = false; } }
function currentJsonText() { return JSON.stringify(serializeMacroDocument(name.value, macro.value), null, 2); }
function showToast(text) { toast.value = text; clearTimeout(toastTimer); toastTimer = window.setTimeout(() => { toast.value = ""; }, 2200); }
function applyJsonText(text, successMessage) { const data = normalizeMacroDocument(JSON.parse(text)); macro.value = data.macro; name.value = data.name; jsonPreview.value = JSON.stringify(data, null, 2); message.value = successMessage; }
function download() { try { const text = currentJsonText(); const url = URL.createObjectURL(new Blob([text], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = `${name.value || 'macro'}.json`; link.click(); URL.revokeObjectURL(url); message.value = "已导出 2.0 宏 JSON。"; } catch (error) { message.value = error.message; } }
async function copyText(text, successMessage) { if (!navigator.clipboard?.writeText) throw new Error("当前浏览器不允许写入剪贴板。"); await navigator.clipboard.writeText(text); message.value = successMessage; }
async function copyJson() { try { const text = currentJsonText(); jsonPreview.value = text; await copyText(text, "JSON 已复制到剪贴板。"); showToast("复制成功"); } catch (error) { message.value = error.message; } }
async function pasteJson() { try { if (!navigator.clipboard?.readText) throw new Error("当前浏览器不允许读取剪贴板。"); applyJsonText(await navigator.clipboard.readText(), "已从剪贴板粘贴 JSON，保存后才会写入 Flash。"); showToast("粘贴成功"); } catch (error) { message.value = error.message || "剪贴板中不是有效的宏 JSON。"; } }
function showJson() { try { jsonPreview.value = currentJsonText(); jsonPreviewVisible.value = !jsonPreviewVisible.value; } catch (error) { message.value = error.message; } }
function isStepGamepadExamplesVisible(step) { return stepGamepadExamplesOverrides.value.has(step) ? stepGamepadExamplesOverrides.value.get(step) : gamepadExamplesVisible.value; }
function toggleGamepadExamples() { gamepadExamplesVisible.value = !gamepadExamplesVisible.value; stepGamepadExamplesOverrides.value = new Map(); }
function toggleStepGamepadExamples(step) { const overrides = new Map(stepGamepadExamplesOverrides.value); overrides.set(step, !isStepGamepadExamplesVisible(step)); stepGamepadExamplesOverrides.value = overrides; }
async function copyPreview() { try { await copyText(jsonPreview.value, "已复制页面中展示的 JSON。"); } catch (error) { message.value = error.message; } }
async function upload(event) { const selected = event.target.files?.[0]; if (!selected) return; try { applyJsonText(await selected.text(), "宏已导入为本地草稿，保存后才会写入 Flash。"); } catch (error) { message.value = error.message || "无法读取这个宏 JSON。"; } event.target.value = ""; }
</script>
<template>
  <Transition name="toast"><div v-if="toast" class="json-toast" role="status">✓ {{ toast }}</div></Transition>
  <PageTitle eyebrow="MACRO EDITOR / 完整宏" :title="`编辑槽位 ${slotIndex+1}`" description="一个宏就是一轮完整操作。每个动作都能设置按键保持时间和松开后的等待时间。"><div class="hero-actions"><button class="secondary" @click="router.push('/scripts')">返回宏设置</button></div></PageTitle>
  <section class="editor-card"><div class="editor-meta"><label class="field"><span>宏名称（必填）</span><input v-model.trim="name" maxlength="32" placeholder="例如：刷钱路线"></label><label class="field"><span>整轮宏完成后等待 (ms)</span><input v-model.number="macro.loopGapMs" type="number" min="0" max="600000" step="100"></label><div><span class="muted">完整宏</span><strong>{{ macro.steps.length }} 个动作 · {{ Math.round(macroCycleMs(macro)/1000) }} 秒/轮</strong></div></div>
    <div class="editor-toolbar"><label class="secondary file-button">导入 JSON 文件<input ref="file" type="file" accept=".json,application/json" @change="upload"></label><button class="secondary" @click="download">导出 JSON</button><button class="secondary" @click="copyJson">复制 JSON</button><button class="secondary" @click="pasteJson">粘贴 JSON</button><button class="secondary" @click="showJson">{{ jsonPreviewVisible ? '收起 JSON' : '查看 JSON' }}</button><button class="secondary" :aria-expanded="gamepadExamplesVisible" @click="toggleGamepadExamples">{{ gamepadExamplesVisible ? '收起手柄示例' : '展开手柄示例' }}</button></div>
    <section v-if="jsonPreviewVisible" class="json-preview"><div class="section-head"><div><span class="tag">JSON DATA / 当前宏数据</span><h2>可查看、选中或直接复制</h2></div><button class="primary" @click="copyPreview">复制显示内容</button></div><textarea readonly :value="jsonPreview" spellcheck="false"></textarea></section>
    <div class="step-list"><article v-for="(step,index) in macro.steps" :key="index" class="step-row"><div class="step-heading"><b>动作 {{ index+1 }}</b><div class="step-order-actions"><button class="mini-button" :disabled="index===0" @click="moveStep(index,-1)">↑ 上移</button><button class="mini-button" :disabled="index===macro.steps.length-1" @click="moveStep(index,1)">↓ 下移</button><button class="mini-button insert" @click="addStep(index+1)">＋ 在下方插入</button></div></div><div class="step-time-grid"><label class="field"><span>① 保持 (ms)</span><input v-model.number="step.durationMs" type="number" min="10" max="600000" step="10"></label><label class="field"><span>② 松开后等待 (ms)</span><input v-model.number="step.waitMs" type="number" min="0" max="600000" step="10"></label><aside class="step-action-summary"><span>这一步</span><strong>{{ describeMacroStep(step).title }}</strong><p>{{ describeMacroStep(step).timing }}</p></aside></div><div class="step-row-actions"><button class="mini-button step-gamepad-toggle" :aria-expanded="isStepGamepadExamplesVisible(step)" :aria-label="`${isStepGamepadExamplesVisible(step) ? '收起' : '展开'}动作 ${index+1} 的手柄示例`" :title="`${isStepGamepadExamplesVisible(step) ? '收起' : '展开'}手柄示例`" @click="toggleStepGamepadExamples(step)"><svg class="step-gamepad-icon" :class="{ expanded: isStepGamepadExamplesVisible(step) }" viewBox="0 0 16 16" aria-hidden="true"><path d="m3 6 5 5 5-5" /></svg></button><button class="remove" :disabled="macro.steps.length===1" aria-label="删除此动作" @click="removeStep(index)">×</button></div><div v-if="isStepGamepadExamplesVisible(step)" class="action-pad-wrap"><VirtualGamepad compact editor-layout selectable :model-value="controlsForReport(step)" @update:model-value="updateControls(step,$event)" /></div></article></div><button class="secondary add-step-button" @click="addStep()">＋ 添加动作</button>
    <p v-if="message" class="form-message">{{ message }}</p><div class="action-row"><button class="primary" :disabled="!device.ready || loading" @click="save">{{ loading ? '处理中…' : '保存到槽位 '+(slotIndex+1) }}</button></div>
  </section>
</template>
